In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
'''import pickle
filename="Loaddata.sav"
pickle.dump(dataset,open("Loaddata.sav","wb"))'''

'import pickle\nfilename="Loaddata.sav"\npickle.dump(dataset,open("Loaddata.sav","wb"))'

In [6]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [7]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [8]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dependent=dataset[['charges']]

In [10]:
# Standard Scaler
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
independent=sc.fit_transform(independent)

In [11]:
import pickle
filename="ScSaveToFile.sav"
pickle.dump(sc,open(filename,"wb"))
scaler=pickle.load(open("ScSaveToFile.sav","rb"))

In [13]:
# model creation using GridSearchCV
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
params_grid={"kernel":['rbf','poly','linear','sigmoid'],
             'C':[10,100,1000,2000,3000],
             'gamma':['auto','scale']}
grid=GridSearchCV(SVR(),params_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'poly', 'linear', 'sigmoid']},
             verbose=3)

In [15]:
print(grid.best_params_)
re=grid.cv_results_

{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}

In [16]:
grid_prediction = grid.predict(independent)
# r2 evaluation 
from sklearn.metrics import r2_score
r_score=r2_score(dependent,grid_prediction)

In [17]:
print( "The Best parameter {}".format(grid.best_params_), " and R2 Score value{}".format(r_score))

The Best parameter {'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}  and R2 Score value0.8382747818757238

In [18]:
# save model 
import pickle
filename="PreprocessedInputFile.sav"

In [19]:
pickle.dump(grid,open(filename,"wb"))
load_model=pickle.load(open("PreprocessedInputFile.sav","rb"))

In [20]:
result=load_model.predict([[52,28,2,1,0]])

In [21]:
result

array([17144.08729473])